# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8088

# mysql
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 1234
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss